FROM openjdk:22-jdk
WORKDIR /app
COPY target/*.jar app.jar

ENV PAYMENT_CANCEL_URL=$PAYMENT_CANCEL_URL
ENV PAYMENT_SUCCESS_URL=$PAYMENT_SUCCESS_URL
ENV POUT_POLICY_DESCRIPTION=$POUT_POLICY_DESCRIPTION
ENV POUT_POLICY_NOTIFICATION_MESSAGE=$POUT_POLICY_NOTIFICATION_MESSAGE
ENV SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD
ENV SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL
ENV SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME
ENV SPRING_RABBITMQ_HOST=$SPRING_RABBITMQ_HOST
ENV SPRING_RABBITMQ_PASSWORD=$SPRING_RABBITMQ_PASSWORD
ENV SPRING_RABBITMQ_PORT=$SPRING_RABBITMQ_PORT
ENV SPRING_RABBITMQ_SSL_ENABLED=$SPRING_RABBITMQ_SSL_ENABLED
ENV SPRING_RABBITMQ_USERNAME=$SPRING_RABBITMQ_USERNAME
ENV SPRING_RABBITMQ_VIRTUAL_HOST=$SPRING_RABBITMQ_VIRTUAL_HOST
ENV STRIPE_ACCOUNT_ID=$STRIPE_ACCOUNT_ID
ENV STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]